apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tenzai-crawler
spec:
  serviceName: tenzai-crawler
  replicas: 1
  selector:
    matchLabels:
      app: tenzai-crawler
  template:
    metadata:
      labels:
        app: tenzai-crawler
    spec:
      containers:
        - name: tenzai-crawler
          image: tenzai-crawler:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
