events {}

http {
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  upstream site_a { server site-a:8000; }
  upstream site_b { server site-b:8000; }
  upstream site_c { server site-c:8000; }
  upstream site_d { server site-d:8000; }
  upstream site_e { server site-e:8000; }
  upstream site_f { server site-f:8000; }
  upstream auth_a { server auth-a:8000; }
  upstream auth_b { server auth-b:8000; }
  upstream auth_c { server auth-c:8000; }
  upstream auth_d { server auth-d:8000; }
  upstream auth_e { server auth-e:8000; }
  upstream auth_f { server auth-f:8000; }
  upstream auth_g { server auth-g:8000; }
  upstream auth_h { server auth-h:8000; }
  upstream auth_i { server auth-i:8000; }
  upstream auth_j { server auth-j:8000; }
  upstream auth_k { server auth-k:8000; }
  upstream auth_l { server auth-l:8000; }
  upstream auth_m { server auth-m:8000; }
  upstream auth_o { server auth-o:8000; }

  server {
    listen 9101;
    location / { proxy_pass http://site_a; }
  }

  server {
    listen 9102;
    location / { proxy_pass http://site_b; }
  }

  server {
    listen 9103;
    location / { proxy_pass http://site_c; }
  }

  server {
    listen 9104;
    location / { proxy_pass http://site_d; }
  }

  server {
    listen 9105;
    location / { proxy_pass http://site_e; }
  }

  server {
    listen 9106;
    location / { proxy_pass http://site_f; }
  }

  server {
    listen 9201;
    location / { proxy_pass http://auth_a; }
  }

  server {
    listen 9202;
    location / { proxy_pass http://auth_b; }
  }

  server {
    listen 9203;
    location / { proxy_pass http://auth_c; }
  }

  server {
    listen 9204;
    location / { proxy_pass http://auth_d; }
  }

  server {
    listen 9205;
    location / { proxy_pass http://auth_e; }
  }

  server {
    listen 9206;
    location / { proxy_pass http://auth_f; }
  }

  server {
    listen 9207;
    location / { proxy_pass http://auth_g; }
  }

  server {
    listen 9208;
    location / { proxy_pass http://auth_h; }
  }

  server {
    listen 9209;
    location / { proxy_pass http://auth_i; }
  }

  server {
    listen 9210;
    location / { proxy_pass http://auth_j; }
  }

  server {
    listen 9211;
    location / { proxy_pass http://auth_k; }
  }

  server {
    listen 9212;
    location / { proxy_pass http://auth_l; }
  }

  server {
    listen 9213;
    location / { proxy_pass http://auth_m; }
  }

  server {
    listen 9215;
    location / { proxy_pass http://auth_o; }
  }
}
